pub mod categoria;
pub mod cliente;
pub mod compra;
pub mod movimiento;
pub mod producto;
pub mod proveedor;
pub mod resolucion;
pub mod tecnologia;
pub mod venta;

pub use categoria::*;
pub use cliente::*;
pub use compra::*;
pub use movimiento::*;
pub use producto::*;
pub use proveedor::*;
pub use resolucion::*;
pub use tecnologia::*;
pub use venta::*;
